# Generated by Django 2.2.28 on 2023-05-25 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=15)),
                ('poste', models.CharField(choices=[('Technicien', 'Technicien - Takes care of the maintenance'), ('Manager', 'Manager - Lead a team of Technicien'), ('Employee', 'Employee - Work on the PC/Mac at the office'), ('Administrator', 'Administrator - Install the network and maintain it')], default='Employee', max_length=32)),
                ('etat', models.CharField(choices=[('connecte', 'Utilisateur en ligne'), ('hors ligne', 'Utilisateur hors ligne')], default='connecte', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('maintenanceDate', models.DateField(default=datetime.date.today)),
                ('mach', models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'MAc - Run MacOS'), ('Serveur', 'Serveur - Run some services (web,ftp)'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32)),
                ('etat', models.CharField(choices=[('en ligne', 'machine is online'), ('hors ligne', 'machine is offline'), ('maintenance', 'machine restarting')], default='en ligne', max_length=16)),
                ('personnel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.Personnel')),
            ],
        ),
    ]
