# Generated by Django 4.2.1 on 2023-05-12 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='owner',
            field=models.ForeignKey(default='Aucun', on_delete=django.db.models.deletion.SET_DEFAULT, to='project.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 23, 9, 1, 727986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Technicien', 'Technicien - Takes care of the maintenance'), ('Manager', 'Manager - Lead a team of Technicien'), ('Employee', 'Employee - Work on the PC/Mac at the office'), ('Administrator', 'Administrator - Install the network and maintain it')], default='Employee', max_length=32),
        ),
    ]
