# Generated by Django 4.2.1 on 2023-05-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_machine_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='naissance',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 20, 46, 44, 21783, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 20, 46, 44, 71049, tzinfo=datetime.timezone.utc)),
        ),
    ]
