# Generated by Django 4.2.1 on 2023-05-12 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_machine_owner_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 23, 25, 30, 108502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.personnel'),
        ),
    ]
