# Generated by Django 4.2.1 on 2023-05-13 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_personnel_naissance_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 20, 52, 4, 142245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='naissance',
            field=models.DateField(),
        ),
    ]
