# Generated by Django 4.2.1 on 2023-05-12 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_machine_maintenancedate_alter_machine_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='id',
            new_name='id_machine',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='owner',
            new_name='id_personnel',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='id',
            new_name='id_machine',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 23, 28, 16, 548343, tzinfo=datetime.timezone.utc)),
        ),
    ]
