# Generated by Django 4.2.1 on 2023-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
