# Generated by Django 4.2.1 on 2023-05-12 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_id_machine_machine_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='personnel',
            new_name='personnel_id',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 23, 33, 20, 657816, tzinfo=datetime.timezone.utc)),
        ),
    ]
