# Generated by Django 4.2.1 on 2023-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_machine_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('lieu', models.CharField(max_length=30)),
                ('reseau', models.GenericIPAddressField(default='0.0.0.0')),
            ],
        ),
    ]
