# Generated by Django 4.2.1 on 2023-06-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='lieu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.infrastructure'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
