# Generated by Django 4.2.1 on 2023-05-13 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 20, 56, 51, 789012, tzinfo=datetime.timezone.utc)),
        ),
    ]
