# Generated by Django 4.2.1 on 2023-05-12 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_personnel_id_machine_personnel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='personnel_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='personnel',
        ),
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 23, 35, 13, 885277, tzinfo=datetime.timezone.utc)),
        ),
    ]
