# Generated by Django 4.2.1 on 2023-05-12 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_personnel_id_personnel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 23, 36, 34, 127808, tzinfo=datetime.timezone.utc)),
        ),
    ]
