# Generated by Django 4.2.1 on 2023-05-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_machine_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'MAc - Run MacOS'), ('Serveur', 'Serveur - Run some services (web,ftp)'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32),
        ),
    ]
