# Generated by Django 4.2.1 on 2023-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_machine_mach'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='etat',
            field=models.CharField(choices=[('en ligne', 'machine is online'), ('hors ligne', 'machine is offline'), ('maintenance', 'machine restarting')], default='en ligne', max_length=16),
        ),
    ]
