from django.urls import path
from . import views
from django.contrib import admin


urlpatterns = [
    path('admin/login/', views.login, name='login'),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('liste_personnel/', views.liste_personnel, name='liste_personnel'),
    path('liste_machine/', views.liste_machine, name='liste_machine'),
    path('machine/<pk>',
         views.machine_view,
         name='machine_view'),
    path('personnel/<pk>',
         views.personnel_view,
         name='personnel_view'),
    path('ajout_machine_personnel/',
          views.add_machine_personnel, 
          name='ajout_machine_personnel'),
     path('supprimer_machine/<pk>',
          views.supprimer_machine,
          name='supprimer_machine'),
     path('supprimer_personnel/<pk>',
          views.supprimer_personnel,
          name='supprimer_personnel'),
     path('chatbot',
          views.chatbot,
          name='chatbot'),
     path('login',
          views.login,
          name='login'),
     path('profile',
          views.profile,
          name='profile'),
     path('forbidden/', views.profile, name='forbidden'),
     path('logout/', views.logout, name='logout'),
     path('edit_machine/<pk>',
          views.edit_machine,
          name='edit_machine'),
     path('edit_personnel/<pk>',
          views.edit_personnel,
          name='edit_personnel'),
     path('recherche/', views.recherche, name='recherche'),
]